config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/pets', to: 'pets#index'
  get '/pets/new', to: 'pets#new', as: :new_pet
  get '/pets/:id', to: 'pets#show', as: :pet
  post '/pets', to: 'pets#create'
  delete '/pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(fish dog sloth human centipede lion cat rabbit)
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [:show, :destroy]
  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def find_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllThePetsAreMissing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <%= simple_form_for(@pet) do |f| %>
    <%= f.input :name %>
    <%= f.input :species, collection: Pet::SPECIES %>
    <%= f.input :address %>
    <%= f.input :found_on %>
    <%= f.submit %>
  <% end %>
</div>

<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Pets</h1>

<%= link_to 'New pet', new_pet_path %>

<% @pets.each do |pet| %>
  <h1><%= link_to pet.name, pet_path(pet) %></h1>
<% end %>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p> <%= @pet.address %> </p>
<p> <%= @pet.species %> </p>
<p> <%= @pet.found_on %> </p>

<%= link_to 'delete', pet_path(@pet), method: :delete %>
<%= link_to 'Back', pets_path %>